---
- name: Confluence | Setting confluence path in config
  lineinfile:
    path:
      "{{ confluence_home_path }}/{{ confluence_pkg }}/confluence/\
      WEB-INF/classes/confluence-init.properties"
    regexp: 'confluence\.home'
    line: "confluence.home={{ confluence_data_path }}"
    state: present
  notify: Confluence | Service restart

- name: Confluence | Setting confluence config
  template:
    src: "{{ confluence_server_config_file }}"
    dest: "{{ confluence_home_path }}/{{ confluence_pkg }}/conf/server.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: '0644'
  notify: Confluence | Service restart

- name: Confluence | Setting Catalina config
  template:
    src: "{{ confluence_catalina_config_file }}"
    dest: "{{ confluence_home_path }}/{{ confluence_pkg }}/bin/setenv.sh"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: '0644'
  notify: Confluence | Service restart

- name: Confluence | Setting database link type
  ansible.builtin.lineinfile:
    path: "{{ confluence_data_path }}/confluence.cfg.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: "0640"
    regexp: "hibernate.connection.driver_class"
    line: '<property name="hibernate.connection.driver_class">{{ confluence_database_configuration.driver }}</property>'
    insertbefore: "</properties>"
  notify: Confluence | Service restart

- name: Confluence | Setting database link dialect
  ansible.builtin.lineinfile:
    path: "{{ confluence_data_path }}/confluence.cfg.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: "0640"
    regexp: "hibernate.dialect"
    line: '<property name="hibernate.dialect">{{ confluence_database_configuration.dialect }}</property>'
    insertbefore: "</properties>"
  notify: Confluence | Service restart

- name: Confluence | Setting database url
  ansible.builtin.lineinfile:
    path: "{{ confluence_data_path }}/confluence.cfg.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: "0640"
    regexp: "hibernate.connection.url"
    line: '<property name="hibernate.connection.url">{{ confluence_database_configuration.url }}</property>'
    insertbefore: "</properties>"
  notify: Confluence | Service restart

- name: Confluence | Setting database user
  ansible.builtin.lineinfile:
    path: "{{ confluence_data_path }}/confluence.cfg.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: "0640"
    regexp: "hibernate.connection.username"
    line: '<property name="hibernate.connection.username">{{ confluence_database_configuration.user }}</property>'
    insertbefore: "</properties>"
  notify: Confluence | Service restart

- name: Confluence | Setting database password
  ansible.builtin.lineinfile:
    path: "{{ confluence_data_path }}/confluence.cfg.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode: "0640"
    regexp: "hibernate.connection.password"
    line: '<property name="hibernate.connection.password">{{ confluence_database_configuration.password }}</property>'
    insertbefore: "</properties>"
  no_log: true
  notify: Confluence | Service restart

- name: Confluence | Setting logs location
  template:
    src: "{{ confluence_logging_properties_file }}"
    dest:
      "{{ confluence_home_path }}/{{ confluence_pkg }}/conf/logging.properties"
    mode: '0644'
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
  notify: Confluence | Service restart

- name: Confluence | Copying logrotate config
  template:
    src: "{{ confluence_logrotate_config_file }}"
    dest: /etc/logrotate.d/confluence
    mode: 0644
    owner: root
    group: root
  when: confluence_logrotate_enabled | bool
